# Generated by Django 2.1.7 on 2019-03-25 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizresponse',
            name='q1',
        ),
        migrations.RemoveField(
            model_name='quizresponse',
            name='q2',
        ),
        migrations.RemoveField(
            model_name='quizresponse',
            name='q3',
        ),
        migrations.RemoveField(
            model_name='quizresponse',
            name='q4',
        ),
        migrations.AddField(
            model_name='quizresponse',
            name='q1_attentive',
            field=models.BooleanField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quizresponse',
            name='q2_hope',
            field=models.BooleanField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quizresponse',
            name='q3_empathetic',
            field=models.BooleanField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quizresponse',
            name='q4_humor',
            field=models.BooleanField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quizresponse',
            name='q5_anxiety',
            field=models.BooleanField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quizresponse',
            name='q6_sleep',
            field=models.BooleanField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quizresponse',
            name='q7_appetite',
            field=models.BooleanField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quizresponse',
            name='q8_mood',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
