# Generated by Django 2.1.7 on 2019-02-28 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activityType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.ActivityType'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='caretaker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.Caretaker'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='elderly',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.Elderly'),
        ),
    ]
