# Generated by Django 2.1.7 on 2019-03-25 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_auto_20190325_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizresponse',
            name='q1_attentive',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='quizresponse',
            name='q2_hope',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='quizresponse',
            name='q3_empathetic',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='quizresponse',
            name='q4_humor',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='quizresponse',
            name='q5_anxiety',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='quizresponse',
            name='q6_sleep',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='quizresponse',
            name='q7_appetite',
            field=models.BooleanField(default=True),
        ),
    ]
