# Generated by Django 2.1.7 on 2019-02-28 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_auto_20190228_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='caretaker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.Caretaker'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='elderly',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.Elderly'),
        ),
        migrations.AlterField(
            model_name='quizresponse',
            name='caretaker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.Caretaker'),
        ),
        migrations.AlterField(
            model_name='quizresponse',
            name='elderly',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.Elderly'),
        ),
    ]
