# Generated by Django 2.1.7 on 2019-04-08 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0006_auto_20190325_2340'),
    ]

    operations = [
        migrations.AddField(
            model_name='elderly',
            name='picture',
            field=models.TextField(blank=True),
        ),
    ]
