# Generated by Django 2.1.7 on 2019-04-08 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0007_elderly_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizresponse',
            name='q7_appetite_new',
            field=models.IntegerField(default=0),
        ),
    ]
