# Generated by Django 2.1.7 on 2019-04-08 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0008_quizresponse_q7_appetite_new'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizresponse',
            name='q7_appetite',
        ),
    ]
